### ISSUE TITLE
avoiding the duplicated beanstalkd_pass directive

### ISSUE THREAD

**Issue by aCayF** [calio/beanstalkd-nginx-module#2]
hi @calio 
   if it is better or not to use the static global variable  `ngx_http_beanstalkd_enabled` to check the duplicated `beanstalkd_pass` directive?
   [related source code](https://github.com/calio/beanstalkd-nginx-module/blob/master/src/ngx_http_beanstalkd_module.c#L205)

**Comment by calio** [comment]
I think you are right. Could you submit a patch for this?

**Comment by aCayF** [comment]
No problem, patch is on the way:)

**Comment by aCayF** [comment]
https://github.com/calio/beanstalkd-nginx-module/pull/3

**Comment by calio** [comment]
I've looked at the code again. It' wrong to check "blcf->upstream.upstream" to see if there are duplicated "beanstalkd_pass" directives. But it's also wrong to check "ngx_http_beanstalkd_enabled" because it's a global viable. So that means if we write "beanstalkd_pass" somewhere, we can't write another "beanstalkd_pass" even in different server blocks. So it better to add a flag in this module's location configuration "blcf", and check this flag instead.

**Comment by aCayF** [comment]
that is really what i haven't thought about, so
1. dose flag `conf->duplicated_pass` fit in the situation we met? 
2. if yes, which merge scheme should i use for merging the flag?
3. what does the global variable `ngx_http_beanstalkd_enabled` mean to do?
thx

**Comment by calio** [comment]
1. Yes, but I think you may need a better name for conf->duplicated_pass
2. you can use ngx_conf_merge_uint_value
3. Is of no use, should remove it.

**Comment by aCayF** [comment]
i think there are three cases we should care about here,
1 `beanstalkd_pass` directives appear in the same location

```
server {
  location /bar {
     beanstalkd_pass
     beanstalkd_pass
  }
}
```

2  `beanstalkd_pass` directives appear in different nested locations

```
server {
    location /foo {
       beanstalkd_pass
       location /bar {
          beanstalkd_pass
       }
    }
}
```

3  `beanstalkd_pass` directives appear in different parallel locations

```
server {
    location /foo {
       beanstalkd_pass
    }
    location /bar {
       beanstalkd_pass
    }
}
```

as we can see, the first one is what we mean to be forbiddened, and the other two are permitted,
so the flag (i.e. `blcf->beanstalkd_enabled`)we used to achieve this, should be hardcoded to zero when we first create the loc conf, and we shouldn't use any merge scheme for the flag as otherwise it will inherit value from its parent conf in the # 2 case above.
am i right or not with this consideration?
thx

**Comment by aCayF** [comment]
i think we can use a more efficient method here,

```
if (blcf->upstream.upstream || blcf->complex_target) {
    return "is duplicate";     
}
```

we still keep `blcf->upstream.upstream` in the if statement, moreover, we introduce the `blcf->complex_target` into it with an  or operator
and that is exactly the same as what proxy module did for checking the duplicated `proxy_pass`

**Comment by calio** [comment]
It's not that complicated. "beanstalkd_pass" is only allowed in location context as it has only one flag "NGX_HTTP_LOC_CONF". So 2 is an illegal configuration. "blcf->beanstalkd_enabled" works for 1 and 3.

**Comment by aCayF** [comment]
so, if i want the `beanstalkd_pass` directive to be permitted in the # 2 case, what other flags should be added to `NGX_HTTP_LOC_CONF` ?

**Comment by aCayF** [comment]
related patch is here https://github.com/calio/beanstalkd-nginx-module/pull/4
